// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egrtlgwdndzfhvpmgsal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVncnRsZ3dkbmR6Zmh2cG1nc2FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzY5NzMsImV4cCI6MjA2NjM1Mjk3M30.km_oPFwIFr1GPKSrO5iRBHV0CR4NaNjyIIWRMN8vcc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);